Repository NVIDIA/nvidia-resiliency-ext, pull requests merged in 2025-07, with the labels that each got.

#104 use spawn for improved stability
  src/nvidia_resiliency_ext/checkpointing/async_ckpt/filesystem_async.py
Labels: ci-approved

#103 InProcess torch.cuda.empty_cache() in Finalize should apply to the right device
  src/nvidia_resiliency_ext/inprocess/finalize.py
Labels: ci-approved

#106 Updating async ckpt documentation
  docs/source/checkpointing/async/usage_guide.rst
Labels: documentation

#112 Rhewett/fix leaky restart
  src/nvidia_resiliency_ext/inprocess/rank_assignment.py
  src/nvidia_resiliency_ext/inprocess/wrap.py
Labels: ci-approved, backport: release/v0.4.0

#110 Update README.md with github.io links
  README.md
Labels: documentation

#117 local checkpoint: update async usage to persistence=False
  docs/source/checkpointing/local/usage_guide.rst
  examples/checkpointing/local_ckpt.py
Labels: ci-approved

#121 Update release-notes.md for v0.4.1
  docs/source/release-notes.md
Labels: ci-approved

#124 Cherry-pick PRs into release/v0.4.0
  docs/source/release-notes.md
Labels: ci-approved

#100 Moved GPU health check out of Rendezvous join operation
  src/nvidia_resiliency_ext/fault_tolerance/_ft_rendezvous.py
  tests/fault_tolerance/unit/test_dynamic_rendezvous.py
Labels: ci-approved

#128 [Build] Improvements to CUDA path detection during source installation
  cupti_build.py
Labels: ci-approved
